"""Groq-powered AI questions for equipment incident reporting.

Generates equipment-specific condition questions for the two-way SMS flow.
Degrades gracefully: if no API key is set or the request fails, callers get
the static CONDITION_MENU fallback.
"""

import logging

from app.config import get_settings
from app.models import Equipment

logger = logging.getLogger(__name__)


def _client():
    settings = get_settings()
    if not settings.groq_api_key:
        return None
    try:
        from groq import Groq

        return Groq(api_key=settings.groq_api_key)
    except Exception as exc:  # pragma: no cover - import/binding failure
        logger.warning("Groq client unavailable: %s", exc)
        return None


def equipment_questions(equipment: Equipment) -> list[str]:
    """Return a short list (<=6) of likely problem conditions for this
    equipment, generated by Groq.  Falls back to the static menu when AI
    is unavailable or produces no usable output.

    The list is ordered and the labels are one-line (SMS friendly).
    """
    try:
        questions = _ask_groq(equipment)
    except Exception as exc:
        logger.warning("Groq equipment_questions failed for %s: %s", equipment.code, exc)
        questions = []

    if not questions:
        from app.services.conversation import CONDITION_MENU

        questions = list(CONDITION_MENU.values())

    unique = []
    for label in questions:
        clean = " ".join(str(label).split())
        if clean and clean not in unique:
            unique.append(clean)

    return unique[:6]


def _ask_groq(equipment: Equipment) -> list[str]:
    client = _client()
    if client is None:
        return []

    settings = get_settings()
    prompt = (
        "You write short maintenance questions for factory workers using SMS. "
        f"The equipment to troubleshoot is:\n"
        f"- Name: {equipment.name}\n"
        f"- Code: {equipment.code}\n"
        f"- Type: {equipment.equipment_type}\n"
        f"- Location: {equipment.location}\n\n"
        "List the 4-6 most likely problems/conditions for THIS specific equipment "
        "that a worker might report. Rules:\n"
        "- One problem per line, no numbering, no bullets, no quotes.\n"
        "- Each line at most 60 characters.\n"
        "- Use plain English, no special characters.\n"
        "- Cover different fault families (leaks, temperature, power, stoppage, "
        "mechanical/ noise, other) tailored to this equipment type.\n"
    )
    completion = client.chat.completions.create(
        model=settings.groq_model,
        messages=[
            {
                "role": "system",
                "content": "You generate concise equipment troubleshooting menus. "
                "Reply with plain lines only.",
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.3,
        max_tokens=512,
    )
    text = (completion.choices[0].message.content or "").strip()
    if not text:
        return []

    questions = []
    for line in text.splitlines():
        line = line.strip().lstrip("0123456789.-* ")
        if line:
            questions.append(line)
    return questions