import logging

from app.config import get_settings
from app.services.africastalking import get_sms, _SDK_AVAILABLE

logger = logging.getLogger(__name__)


def send_acknowledgement(phone: str, equipment_label: str, incident_id: int) -> None:
    settings = get_settings()
    message = (
        f"Thibitisha: Thank you for your report. Incident #{incident_id} logged"
        + (f" for {equipment_label}" if equipment_label else "")
        + ". Maintenance has been notified."
    )
    _send(phone, message, settings)


def send_prompt(phone: str, equipment_code: str, questions: list[str] | None = None) -> None:
    """Ask the worker to pick the equipment condition from a numbered menu.

    ``questions`` are the equipment-specific options generated by Groq;
    fall back to the generic condition list when absent.
    """
    settings = get_settings()
    if not questions:
        from app.services.conversation import CONDITION_MENU

        questions = list(CONDITION_MENU.values())
    lines = [f"Thibitisha: {equipment_code}. What's the problem?"]
    lines.extend(f"{i}. {label}" for i, label in enumerate(questions, start=1))
    lines.append("Reply with a number or describe the issue.")
    _send(phone, "\n".join(lines), settings)


def _send(phone: str, message: str, settings) -> None:
    if not settings.africastalking_send_ack:
        return
    if not _SDK_AVAILABLE:
        logger.warning(
            "SMS skipped (%r) to %s: africastalking SDK not installed", message, phone
        )
        return
    if not settings.africastalking_api_key or (
        not settings.africastalking_sandbox and not settings.africastalking_username
    ):
        logger.warning("SMS skipped (%r) to %s: Africa's Talking credentials are not set", message, phone)
        return

    sms = get_sms()
    response = None
    last_error = None
    for attempt in range(1, 4):
        try:
            response = sms.send(
                message=message,
                recipients=[phone],
                sender_id=settings.africastalking_sender_id or None,
            )
            break
        except Exception as exc:
            last_error = exc
            if attempt < 3:
                logger.warning(
                    "SMS attempt %s/3 to %s failed (%s) — retrying",
                    attempt,
                    phone,
                    type(exc).__name__,
                )
    if response is None:
        logger.error(
            "Failed to send SMS to %s after 3 attempts: %s",
            phone,
            last_error,
        )
        return

    logger.info(
        "Reply SMS sent to %s: %r (response=%s)",
        phone,
        message,
        response,
    )
